services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8
    container_name: go-db-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    networks:
      - app-network
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge